import { jsPDF } from "jspdf";
import { NextResponse } from "next/server";

export async function POST(req: Request) {
    try {
        // Parse the form data (hidden form submit sends URL-encoded body)
        const formData = await req.formData().catch(() => null);
        let tripName = "Trip";
        let itinerary: any[] = [];

        if (formData) {
            // From hidden form POST
            const raw = formData.get("payload");
            if (raw) {
                const parsed = JSON.parse(raw as string);
                tripName = parsed.tripName ?? "Trip";
                itinerary = parsed.itinerary ?? [];
            }
        } else {
            // Fallback: JSON body
            const body = await req.json();
            tripName = body.tripName ?? "Trip";
            itinerary = body.itinerary ?? [];
        }

        // Strip non-Latin-1 chars (jsPDF Helvetica limitation)
        const safe = (s: string) => s.replace(/[^\x20-\x7E\xA0-\xFF]/g, "");
        const safeName = safe(tripName);

        const doc = new jsPDF();
        const pageW = doc.internal.pageSize.getWidth();
        let y = 20;

        // Title
        doc.setFontSize(22);
        doc.setFont("helvetica", "bold");
        doc.text(`${safeName} - Itinerary`, pageW / 2, y, { align: "center" });
        y += 8;
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(120);
        doc.text(`Generated by SyncRoute  |  ${itinerary.length} Days`, pageW / 2, y, { align: "center" });
        doc.setTextColor(0);
        y += 6;
        doc.setDrawColor(200);
        doc.line(14, y, pageW - 14, y);
        y += 10;

        for (const day of itinerary) {
            if (y > 260) { doc.addPage(); y = 20; }
            doc.setFontSize(14);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(37, 99, 235);
            doc.text(safe(`${day.day}: ${day.title}`), 14, y);
            doc.setTextColor(0);
            y += 8;

            for (const item of (day.items ?? [])) {
                if (y > 270) { doc.addPage(); y = 20; }
                doc.setFontSize(10);
                doc.setFont("helvetica", "bold");
                doc.text(safe(item.time ?? ""), 18, y);
                doc.setFont("helvetica", "normal");
                const activityLines = doc.splitTextToSize(safe(item.activity ?? ""), pageW - 70);
                doc.text(activityLines, 50, y);
                doc.setTextColor(100);
                doc.setFontSize(9);
                doc.text(safe(item.cost ?? ""), pageW - 14, y, { align: "right" });
                doc.setTextColor(0);
                y += activityLines.length * 5 + 4;
            }
            y += 4;
        }

        const pdfBuffer = doc.output("arraybuffer");
        const fileName = safeName.replace(/[^a-zA-Z0-9]/g, "_") + "_Itinerary.pdf";

        return new NextResponse(pdfBuffer, {
            status: 200,
            headers: {
                "Content-Type": "application/pdf",
                "Content-Disposition": `attachment; filename="${fileName}"`,
                "Content-Length": String(pdfBuffer.byteLength),
            },
        });
    } catch (error) {
        console.error("PDF Generation Error:", error);
        return new NextResponse("Failed to generate PDF", { status: 500 });
    }
}